/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SituacionesDidacticasRouteImport } from './routes/situaciones-didacticas'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ExposicionesRouteImport } from './routes/exposiciones'
import { Route as AutoevaluacionRouteImport } from './routes/autoevaluacion'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as IndexRouteImport } from './routes/index'

const SituacionesDidacticasRoute = SituacionesDidacticasRouteImport.update({
  id: '/situaciones-didacticas',
  path: '/situaciones-didacticas',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposicionesRoute = ExposicionesRouteImport.update({
  id: '/exposiciones',
  path: '/exposiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoevaluacionRoute = AutoevaluacionRouteImport.update({
  id: '/autoevaluacion',
  path: '/autoevaluacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/autoevaluacion': typeof AutoevaluacionRoute
  '/exposiciones': typeof ExposicionesRoute
  '/galeria': typeof GaleriaRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/situaciones-didacticas': typeof SituacionesDidacticasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/autoevaluacion': typeof AutoevaluacionRoute
  '/exposiciones': typeof ExposicionesRoute
  '/galeria': typeof GaleriaRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/situaciones-didacticas': typeof SituacionesDidacticasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/autoevaluacion': typeof AutoevaluacionRoute
  '/exposiciones': typeof ExposicionesRoute
  '/galeria': typeof GaleriaRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/situaciones-didacticas': typeof SituacionesDidacticasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividades'
    | '/autoevaluacion'
    | '/exposiciones'
    | '/galeria'
    | '/quienes-somos'
    | '/situaciones-didacticas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividades'
    | '/autoevaluacion'
    | '/exposiciones'
    | '/galeria'
    | '/quienes-somos'
    | '/situaciones-didacticas'
  id:
    | '__root__'
    | '/'
    | '/actividades'
    | '/autoevaluacion'
    | '/exposiciones'
    | '/galeria'
    | '/quienes-somos'
    | '/situaciones-didacticas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadesRoute: typeof ActividadesRoute
  AutoevaluacionRoute: typeof AutoevaluacionRoute
  ExposicionesRoute: typeof ExposicionesRoute
  GaleriaRoute: typeof GaleriaRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  SituacionesDidacticasRoute: typeof SituacionesDidacticasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/situaciones-didacticas': {
      id: '/situaciones-didacticas'
      path: '/situaciones-didacticas'
      fullPath: '/situaciones-didacticas'
      preLoaderRoute: typeof SituacionesDidacticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposiciones': {
      id: '/exposiciones'
      path: '/exposiciones'
      fullPath: '/exposiciones'
      preLoaderRoute: typeof ExposicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoevaluacion': {
      id: '/autoevaluacion'
      path: '/autoevaluacion'
      fullPath: '/autoevaluacion'
      preLoaderRoute: typeof AutoevaluacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadesRoute: ActividadesRoute,
  AutoevaluacionRoute: AutoevaluacionRoute,
  ExposicionesRoute: ExposicionesRoute,
  GaleriaRoute: GaleriaRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  SituacionesDidacticasRoute: SituacionesDidacticasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
